/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background:              '#081615',
        'surface':               '#081615',
        'surface-dim':           '#081615',
        'surface-card':          '#0B1B1A',
        'surface-elevated':      '#102322',
        'surface-container':     '#142221',
        'surface-container-low': '#101e1d',
        'surface-container-high':'#1f2d2b',
        'surface-container-highest':'#293736',
        'surface-container-lowest':'#041010',
        'surface-bright':        '#2e3c3b',
        'surface-variant':       '#293736',
        'surface-tint':          '#00dfc0',

        'primary':               '#dafff4',
        'primary-container':     '#21f5d4',
        'primary-fixed':         '#34fddc',
        'primary-fixed-dim':     '#00dfc0',
        'on-primary':            '#00382f',
        'on-primary-container':  '#006c5c',
        'on-primary-fixed':      '#00201a',
        'on-primary-fixed-variant':'#005144',
        'inverse-primary':       '#006b5b',

        'secondary':             '#44e9ce',
        'secondary-container':   '#00cdb3',
        'secondary-fixed':       '#5bfbdf',
        'secondary-fixed-dim':   '#31dec3',
        'on-secondary':          '#00382f',
        'on-secondary-container':'#005146',
        'on-secondary-fixed':    '#00201b',
        'on-secondary-fixed-variant':'#005045',

        'tertiary':              '#fff6e7',
        'tertiary-container':    '#ffd754',
        'tertiary-fixed':        '#ffe084',
        'tertiary-fixed-dim':    '#e9c341',
        'on-tertiary':           '#3c2f00',
        'on-tertiary-container': '#745d00',
        'on-tertiary-fixed':     '#231b00',
        'on-tertiary-fixed-variant':'#574500',

        'on-surface':            '#d6e6e3',
        'on-surface-variant':    '#b9cac4',
        'on-background':         '#d6e6e3',
        'inverse-surface':       '#d6e6e3',
        'inverse-on-surface':    '#253332',

        'outline':               '#84948f',
        'outline-variant':       '#3a4a46',

        'error':                 '#ffb4ab',
        'error-container':       '#93000a',
        'on-error':              '#690005',
        'on-error-container':    '#ffdad6',

        'border-glass':          'rgba(255,255,255,0.06)',
        'glow-teal':             'rgba(33,245,212,0.15)',
        'text-primary':          '#F6F6F3',
        'text-muted':            '#8CA5A1',
      },
      fontFamily: {
        'display':    ['"EB Garamond"', 'serif'],
        'headline':   ['"EB Garamond"', 'serif'],
        'body':       ['Inter', 'sans-serif'],
        'label':      ['Inter', 'sans-serif'],
        'display-lg': ['"EB Garamond"', 'serif'],
        'headline-lg':['"EB Garamond"', 'serif'],
        'headline-xl':['"EB Garamond"', 'serif'],
        'body-md':    ['Inter', 'sans-serif'],
        'body-lg':    ['Inter', 'sans-serif'],
        'label-md':   ['Inter', 'sans-serif'],
        'display-lg-mobile': ['"EB Garamond"', 'serif'],
      },
      fontSize: {
        'display-lg':        ['84px',  { lineHeight: '92px',  letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['48px',  { lineHeight: '52px',  letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-xl':       ['60px',  { lineHeight: '68px',  fontWeight: '400' }],
        'headline-lg':       ['40px',  { lineHeight: '48px',  fontWeight: '400' }],
        'body-lg':           ['18px',  { lineHeight: '28px',  fontWeight: '400' }],
        'body-md':           ['16px',  { lineHeight: '24px',  fontWeight: '400' }],
        'label-md':          ['12px',  { lineHeight: '16px',  letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        'gutter':           '32px',
        'margin-mobile':    '24px',
        'margin-desktop':   '80px',
        'container-max':    '1440px',
        'unit':             '8px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      boxShadow: {
        'glass':      '0 4px 30px rgba(0,0,0,0.1), inset 0 0 0 1px rgba(255,255,255,0.05)',
        'glass-hover':'0 8px 40px rgba(0,0,0,0.2), 0 0 20px rgba(33,245,212,0.15)',
        'glow':       '0 0 20px rgba(33,245,212,0.2)',
        'glow-lg':    '0 0 40px rgba(33,245,212,0.3)',
        'score-ring': '0 0 8px rgba(33,245,212,0.5)',
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.65' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")",
        'grid-pattern': "linear-gradient(to right,rgba(255,255,255,0.03) 1px,transparent 1px),linear-gradient(to bottom,rgba(255,255,255,0.03) 1px,transparent 1px)",
        'radial-teal':  'radial-gradient(circle, rgba(33,245,212,0.15) 0%, transparent 70%)',
      },
      backgroundSize: {
        'grid': '40px 40px',
      },
      keyframes: {
        float: {
          '0%':   { transform: 'translateY(0px)' },
          '100%': { transform: 'translateY(-5px)' },
        },
        'float-particle': {
          '0%':   { transform: 'translateY(0) rotate(0deg)', opacity: '0' },
          '50%':  { opacity: '0.5' },
          '100%': { transform: 'translateY(-100vh) rotate(360deg)', opacity: '0' },
        },
        shimmer: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'fade-in-up': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        bounce: {
          '0%,20%,50%,80%,100%': { transform: 'translateY(0)' },
          '40%':                  { transform: 'translateY(-8px)' },
          '60%':                  { transform: 'translateY(-4px)' },
        },
        ping: {
          '75%,100%': { transform: 'scale(2)', opacity: '0' },
        },
        'gradient-shift': {
          '0%':   { backgroundPosition: '0% 50%' },
          '50%':  { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
      },
      animation: {
        'float':          'float 4s ease-in-out infinite alternate',
        'float-slow':     'float 6s ease-in-out infinite alternate',
        'float-slower':   'float 8s ease-in-out infinite alternate',
        'float-particle': 'float-particle 15s linear infinite',
        shimmer:          'shimmer 2s infinite',
        'fade-in-up':     'fade-in-up 0.4s ease-out forwards',
        bounce:           'bounce 2s infinite',
        'gradient-shift': 'gradient-shift 8s ease infinite',
        ping:             'ping 1s cubic-bezier(0,0,0.2,1) infinite',
      },
    },
  },
  plugins: [],
};
